### ISSUE TITLE
TODO for version 1.0

### ISSUE THREAD

**Issue by hsorbo** [hsorbo/ezp2010#1]
This needs to be done.

- [ ] Cleanup error handling
- [ ] Cleanup usb init
- [ ] Create test for read/write commands for all ROMs
- [ ] Progress bar (https://github.com/console-rs/indicatif)
- [x] Fix duplicates in rom-database https://github.com/hsorbo/ezp2010/commit/82f8d6780e5321aaeeeee61e016c90d4dfe80cb3
- [ ] Limit erase to SPI
- [x] Statically link libusb on MacOS
- [ ] `ezp list | head` causes stdout-related panic
